"""Initial Policy schema

Revision ID: 42d3e45f7b56
Revises: 
Create Date: 2026-07-07 03:06:07.776639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d3e45f7b56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('store', sa.String(length=32), nullable=False),
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('store', 'rec_id', name='uq_store_recid'),
    schema='policy'
    )
    with op.batch_alter_table('records', schema='policy') as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_records_rec_id'), ['rec_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_records_store'), ['store'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    schema='policy'
    )
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_table('settings', schema='policy')
    with op.batch_alter_table('records', schema='policy') as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_records_store'))
        batch_op.drop_index(batch_op.f('ix_policy_records_rec_id'))

    op.drop_table('records', schema='policy')
    # ### end Alembic commands ###
