"""Initial ITR schema

Revision ID: 7702e56fa429
Revises: 
Create Date: 2026-07-06 22:27:49.458980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7702e56fa429'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('fy', sa.Text(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('uploaded', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key'),
    schema='itr'
    )
    op.create_table('kv_store',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('key'),
    schema='itr'
    )
    op.drop_table('settings')
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_records_rec_id'))
        batch_op.drop_index(batch_op.f('ix_records_store'))

    op.drop_table('records')
    op.drop_table('alembic_version')
    op.drop_table('kv_store')
    op.drop_table('files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fy', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('files_pkey'))
    )
    op.create_table('kv_store',
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('kv_store_pkey'))
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('records',
    sa.Column('pk', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('rec_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('pk', name=op.f('records_pkey')),
    sa.UniqueConstraint('store', 'rec_id', name=op.f('uq_store_recid'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_records_store'), ['store'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_rec_id'), ['rec_id'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('settings_pkey'))
    )
    op.drop_table('kv_store', schema='itr')
    op.drop_table('files', schema='itr')
    # ### end Alembic commands ###
