"""Initial ITR schema

Revision ID: 7702e56fa429
Revises: 
Create Date: 2026-07-06 22:27:49.458980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7702e56fa429'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('fy', sa.Text(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('uploaded', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key'),
    schema='itr'
    )
    op.create_table('kv_store',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('key'),
    schema='itr'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kv_store', schema='itr')
    op.drop_table('files', schema='itr')
    # ### end Alembic commands ###
