server {
    listen 80;

    location / {
        proxy_pass http://portal:8000;
        proxy_set_header Host $host;
    }

    location /itr/ {
        proxy_pass http://itr:5000/;
        proxy_set_header Host $host;
    }

    # NEW: Policy Service
    location /policy/ {
        proxy_pass http://policy:5000/;
        proxy_set_header Host $host;
    }
}